name: Daily Telegram Message

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install requests
        run: |
          pip install requests
          pip install python-telegram-bot
      - name: Run message script
        run: python dinner.py
